//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductGalleryRef
    {
        public int PGRID { get; set; }
        public int fkProjectID { get; set; }
        public int fkMGID { get; set; }
    
        public virtual MediaGalleries MediaGalleries { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
