//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScratchWebsite.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatProjectRef
    {
        public int CPRID { get; set; }
        public int fkProjectID { get; set; }
        public int fkCategoryID { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
