//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScratchWebsite.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaGalleries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MediaGalleries()
        {
            this.ProductGalleryRef = new HashSet<ProductGalleryRef>();
        }
    
        public int MGID { get; set; }
        public string Caption { get; set; }
        public string FilePathOrLink { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<bool> IsThumbnail { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductGalleryRef> ProductGalleryRef { get; set; }
    }
}
